version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.3
    ports:
      - '8084:8080'
    command:
      - start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

